//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADIM_2.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OffersEntities1 : DbContext
    {
        public OffersEntities1()
            : base("name=OffersEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<offers> offers { get; set; }
        public virtual DbSet<productcategories> productcategories { get; set; }
        public virtual DbSet<products> products { get; set; }
    }
}
