//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADIM_2.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class offers
    {
        public int id { get; set; }
        public int productId { get; set; }
        public string offerHead { get; set; }
        public string offerValue { get; set; }
        public Nullable<System.DateTime> offerCreateTime { get; set; }
    
        public virtual products products { get; set; }
    }
}
