//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADIM_2.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products()
        {
            this.offers = new HashSet<offers>();
        }
    
        public int id { get; set; }
        public int categoryId { get; set; }
        public string productName { get; set; }
        public Nullable<System.DateTime> offerCreateTime { get; set; }
        public Nullable<System.DateTime> offerFinishedTime { get; set; }
        public string productImage { get; set; }
        public string productDescription { get; set; }
        public string productSubDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<offers> offers { get; set; }
        public virtual productcategories productcategories { get; set; }
    }
}
